nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-3.6.1.cjs
# httpProxy: "http://127.0.0.1:7890"
# httpsProxy: "http://127.0.0.1:7890"
httpProxy: "http://127.0.0.1:10808"
httpsProxy: "http://127.0.0.1:10808"